FROM alpine:3.16.2
MAINTAINER Vasily Starovoitov

RUN apk --no-cache add ca-certificates tzdata
ENV TZ="Europe/Moscow"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY tracker-server /app/tracker-server

#ENTRYPOINT ["./tracker-server"]
ENTRYPOINT ["/bin/sh", "-ec", "sleep 10000"]